// prisma/seed.ts
import { PrismaClient, FeeType, ReportType } from '@prisma/client'
const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Starting Seed...')

  // 1. Clean up existing data (Optional: Be careful in production!)
  // await prisma.enrollment.deleteMany()
  // await prisma.courseOnSlot.deleteMany()
  // await prisma.slot.deleteMany()
  // await prisma.course.deleteMany()
  // await prisma.room.deleteMany()

  // 2. Create Physical Resources (Rooms)
  const lab1 = await prisma.room.create({
    data: {
      name: 'Computer Lab 1',
      capacity: 15, // Rigid capacity constraint
    },
  })
  console.log(`Created Room: ${lab1.name} (ID: ${lab1.id})`)

  // 3. Create Slots (Time Blocks for Lab 1)
  // Creating a 9:00 AM - 10:00 AM slot for Mon,Tue,Wed
  const slot9to10 = await prisma.slot.create({
    data: {
      roomId: lab1.id,
      startTime: new Date('1970-01-01T09:00:00Z'), // Generic time
      endTime: new Date('1970-01-01T10:00:00Z'),
      days: 'Mon,Tue,Wed',
    },
  })
  console.log(`Created Slot: 9-10 AM (ID: ${slot9to10.id})`)

  // 4. Create Courses
  const courseOffice = await prisma.course.create({
    data: {
      name: 'MS Office Professional',
      durationMonths: 3,
      baseFee: 1500.00,
      feeType: FeeType.MONTHLY,
    },
  })
  
  const courseEnglish = await prisma.course.create({
    data: {
      name: 'English Language',
      durationMonths: 4,
      baseFee: 2000.00,
      feeType: FeeType.MONTHLY,
    },
  })
  console.log('Created Courses: MS Office, English')

  // 5. Assign Courses to the Slot (The "Shared Capacity" Logic)
  // Both MS Office AND English will run in Lab 1 at 9-10 AM
  const assignment1 = await prisma.courseOnSlot.create({
    data: {
      slotId: slot9to10.id,
      courseId: courseOffice.id,
    }
  })

  const assignment2 = await prisma.courseOnSlot.create({
    data: {
      slotId: slot9to10.id,
      courseId: courseEnglish.id,
    }
  })

  console.log('✅ Seeding Completed. Lab 1 is ready for shared enrollment.')

  // 6. Create Default Report Formats
  console.log('📄 Creating default report formats...')

  const reportFormats = [
    {
      reportType: ReportType.MONTHLY,
      name: 'Monthly Fee Collection Report',
      showLogo: true,
      logoPosition: 'top-left',
      logoUrl: null,
      headerText: 'Monthly Fee Collection Summary',
      footerText: 'Generated by Shams Computer Institute Management System',
      titleFontSize: 24,
      titleFontFamily: 'Helvetica-Bold',
      subtitleFontSize: 16,
      subtitleFontFamily: 'Helvetica',
      bodyFontSize: 12,
      bodyFontFamily: 'Helvetica',
      primaryColor: '#1f2937',
      secondaryColor: '#6b7280',
      accentColor: '#3b82f6',
      backgroundColor: '#ffffff',
      pageOrientation: 'portrait',
      pageSize: 'A4',
      marginTop: 50,
      marginBottom: 50,
      marginLeft: 50,
      marginRight: 50,
      showGeneratedDate: true,
      showPageNumbers: true,
      showInstitutionInfo: true,
      institutionName: 'Shams Computer Institute',
      institutionAddress: '123 Education Street, City, State 12345',
      institutionPhone: '+1 (555) 123-4567',
      institutionEmail: 'info@shams.edu',
      monthlyShowStudentDetails: true,
      monthlyShowPaymentHistory: true,
      studentShowFeeBreakdown: false,
      studentShowPaymentTimeline: false,
      courseShowStudentList: false,
      overallShowCharts: false,
      overallShowMonthlyTrends: false
    },
    {
      reportType: ReportType.STUDENT,
      name: 'Student Fee History Report',
      showLogo: true,
      logoPosition: 'top-center',
      logoUrl: null,
      headerText: 'Student Fee History',
      footerText: 'Generated by Shams Computer Institute Management System',
      titleFontSize: 22,
      titleFontFamily: 'Helvetica-Bold',
      subtitleFontSize: 14,
      subtitleFontFamily: 'Helvetica',
      bodyFontSize: 11,
      bodyFontFamily: 'Helvetica',
      primaryColor: '#1f2937',
      secondaryColor: '#6b7280',
      accentColor: '#10b981',
      backgroundColor: '#ffffff',
      pageOrientation: 'portrait',
      pageSize: 'A4',
      marginTop: 40,
      marginBottom: 40,
      marginLeft: 40,
      marginRight: 40,
      showGeneratedDate: true,
      showPageNumbers: true,
      showInstitutionInfo: true,
      institutionName: 'Shams Computer Institute',
      institutionAddress: '123 Education Street, City, State 12345',
      institutionPhone: '+1 (555) 123-4567',
      institutionEmail: 'info@shams.edu',
      monthlyShowStudentDetails: false,
      monthlyShowPaymentHistory: false,
      studentShowFeeBreakdown: true,
      studentShowPaymentTimeline: true,
      courseShowStudentList: false,
      overallShowCharts: false,
      overallShowMonthlyTrends: false
    },
    {
      reportType: ReportType.COURSE,
      name: 'Course Fee Collection Report',
      showLogo: true,
      logoPosition: 'top-right',
      logoUrl: null,
      headerText: 'Course Fee Collection Summary',
      footerText: 'Generated by Shams Computer Institute Management System',
      titleFontSize: 24,
      titleFontFamily: 'Helvetica-Bold',
      subtitleFontSize: 16,
      subtitleFontFamily: 'Helvetica',
      bodyFontSize: 12,
      bodyFontFamily: 'Helvetica',
      primaryColor: '#1f2937',
      secondaryColor: '#6b7280',
      accentColor: '#8b5cf6',
      backgroundColor: '#ffffff',
      pageOrientation: 'landscape',
      pageSize: 'A4',
      marginTop: 50,
      marginBottom: 50,
      marginLeft: 30,
      marginRight: 30,
      showGeneratedDate: true,
      showPageNumbers: true,
      showInstitutionInfo: true,
      institutionName: 'Shams Computer Institute',
      institutionAddress: '123 Education Street, City, State 12345',
      institutionPhone: '+1 (555) 123-4567',
      institutionEmail: 'info@shams.edu',
      monthlyShowStudentDetails: false,
      monthlyShowPaymentHistory: false,
      studentShowFeeBreakdown: false,
      studentShowPaymentTimeline: false,
      courseShowStudentList: true,
      overallShowCharts: false,
      overallShowMonthlyTrends: false
    },
    {
      reportType: ReportType.OVERALL,
      name: 'Institution Fee Overview Report',
      showLogo: true,
      logoPosition: 'top-center',
      logoUrl: null,
      headerText: 'Institution Fee Overview',
      footerText: 'Generated by Shams Computer Institute Management System',
      titleFontSize: 26,
      titleFontFamily: 'Helvetica-Bold',
      subtitleFontSize: 18,
      subtitleFontFamily: 'Helvetica',
      bodyFontSize: 12,
      bodyFontFamily: 'Helvetica',
      primaryColor: '#1f2937',
      secondaryColor: '#6b7280',
      accentColor: '#f59e0b',
      backgroundColor: '#ffffff',
      pageOrientation: 'portrait',
      pageSize: 'A4',
      marginTop: 60,
      marginBottom: 60,
      marginLeft: 50,
      marginRight: 50,
      showGeneratedDate: true,
      showPageNumbers: true,
      showInstitutionInfo: true,
      institutionName: 'Shams Computer Institute',
      institutionAddress: '123 Education Street, City, State 12345',
      institutionPhone: '+1 (555) 123-4567',
      institutionEmail: 'info@shams.edu',
      monthlyShowStudentDetails: false,
      monthlyShowPaymentHistory: false,
      studentShowFeeBreakdown: false,
      studentShowPaymentTimeline: false,
      courseShowStudentList: false,
      overallShowCharts: true,
      overallShowMonthlyTrends: true
    }
  ]

  for (const format of reportFormats) {
    await prisma.reportFormat.upsert({
      where: { reportType: format.reportType },
      update: format,
      create: format
    })
    console.log(`Created/Updated Report Format: ${format.name}`)
  }

  console.log('✅ All report formats seeded successfully.')
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })